import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, FileText, Presentation } from 'lucide-react';
import { format } from 'date-fns';

// Downloads for the decks generated by the export pipelines. The files are stored
// on the report record itself — this surfaces them so they can be fetched later.
export default function GeneratedExportsSection({ report }) {
  const files = [
    { url: report?.claude_pptx_url, label: 'Palsgaard template deck (PPTX)', note: 'Generated from the canonical Palsgaard PowerPoint template', icon: Presentation, at: report?.claude_export_finished_at },
    { url: report?.gamma_pptx_url, label: 'Gamma deck (PPTX)', note: 'Generated via Gamma', icon: Presentation, at: report?.gamma_export_started_at },
    { url: report?.gamma_pdf_url, label: 'Gamma deck (PDF)', note: 'Generated via Gamma', icon: FileText, at: report?.gamma_export_started_at },
  ].filter(f => f.url);

  if (!files.length) return null;

  return (
    <Card className="mb-6">
      <CardHeader>
        <CardTitle className="text-base">Generated deck files</CardTitle>
        <p className="text-sm text-muted-foreground">
          Kept on this report — download them any time, also after the chat session is closed.
        </p>
      </CardHeader>
      <CardContent className="space-y-2">
        {files.map((f, i) => {
          const Icon = f.icon;
          return (
            <div key={i} className="flex items-center gap-3 p-3 rounded-lg border border-border bg-card">
              <Icon className="w-4 h-4 shrink-0" style={{ color: '#1D428A' }} />
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-foreground truncate">{f.label}</p>
                <p className="text-xs text-muted-foreground">
                  {f.note}
                  {f.at ? ` · ${format(new Date(f.at), 'd MMM yyyy HH:mm')}` : ''}
                </p>
              </div>
              <a href={f.url} target="_blank" rel="noopener noreferrer">
                <Button size="sm" variant="secondary">
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
              </a>
            </div>
          );
        })}
      </CardContent>
    </Card>
  );
}